# Generated by Django 5.0.7 on 2025-03-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_of_reviews',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
