# Generated by Django 5.0.7 on 2025-03-17 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0003_alter_product_number_of_reviews_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
