# Generated by Django 5.0.7 on 2025-03-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0008_remove_cart_completed_alter_cartitems_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='is_staff',
        ),
    ]
