# Generated by Django 5.0.7 on 2025-04-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0010_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
