# Generated by Django 5.0.7 on 2025-06-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0014_remove_product_google_drive_image_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('address', models.CharField(max_length=226)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineStore.order')),
            ],
        ),
    ]
