# Generated by Django 5.0.7 on 2025-06-26 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0015_packageform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageform',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='package_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='onlineStore.packageform'),
        ),
    ]
