# Generated by Django 5.0.7 on 2025-06-26 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0016_remove_packageform_order_order_package_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageform',
            old_name='name',
            new_name='customer_name',
        ),
    ]
