# Generated by Django 5.0.7 on 2025-06-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0017_rename_name_packageform_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageform',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
    ]
