# Generated by Django 5.0.7 on 2025-07-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0018_alter_packageform_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_available',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
