# Generated by Django 5.0.7 on 2025-07-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0019_product_number_available_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
