# Generated by Django 5.2.4 on 2026-01-19 23:38

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0022_remove_order_product_name_orderitem_product_name'),
    ]

    operations = [VectorExtension()
    ]
