# Generated by Django 5.2.4 on 2026-01-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0024_product_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
